name: Snake Game

on:
  schedule:
    # Será atualizado a cada 5 horas.
    - cron: "0 */5 * * *"
  workflow_dispatch:  # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Faz checkout do repositório
    - uses: actions/checkout@v2

    # Repositorio que será utilizado para gerar os arquivos.
    - uses: Platane/snk@master
      id: snake-gif
      with:
        github_user_name: maduaperes  # Substitua pelo seu nome de usuário
        gif_out_path: dist/github-contribution-grid-snake.gif  # Gera GIF
        svg_out_path: dist/github-contribution-grid-snake.svg  # Gera SVG

    # Exibe status do git (apenas para verificação)
    - run: git status

    # Faz commit e push das mudanças para o repositório
    - name: Commit changes and push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: output  # Push para o branch 'output'
        force: true

    # Faz deploy do conteúdo para a página GitHub Pages
    - uses: crazy-max/ghaction-github-pages@v2.1.3
      with:
        target_branch: output  # Branch onde os arquivos serão enviados
        build_dir: dist  # Diretório de saída onde os arquivos (GIF, SVG) foram gerados
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
